name: Pull Request Approval for Non-Dependabot PRs

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Run checks
        uses: radenpioneer/astro-check@v0
        with:
          check-command: 'check'
  approve:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: ['check']
    steps:
      # Here the PR gets approved.
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}